apiVersion: v1
kind: Service
metadata:
  labels:
    app: SERVICE_NAME
  name: SERVICE_NAME-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: SERVICE_NAME
  type: ClusterIP
